[base]
latdim = 64 # Embedding size
topk = 20
gpu = "0"
seed = 2233 # Random seed
denoise_dim = "[1024]" # embedding size for denoise layer input/output 
d_emb_size = 10 # time embedding size for diffusion step
cl_method = 1

# ------------------------------------------------------------

[data]
name = "sports" # Dataset name

# ------------------------------------------------------------

[hyper] # Hyperparameters for the model
modal_cl_temp = 0.1 # Temperature in contrastive learning
modal_cl_rate = 0.01 # Weight for contrastive learning
cross_cl_temp = 0.2
cross_cl_rate = 0.1
noise_degree = 0.1

noise_scale = 0.1 # Noise scale
noise_min = 0.0001 # Minimum noise
noise_max = 0.02 # Maximum noise
steps = 5 # Number of steps

sim_weight = 0.1 # Weight of refact_ui_loss
residual_weight = 0.5  # RIS lambda
modal_adj_weight = 0.2

sampling_step = 0 # Initial sampling steps for the inverse diffusion process

# ------------------------------------------------------------

[train]
lr = 0.001 # Learning rate
batch = 1024 # Batch size
test_batch = 1024 # Number of users in a testing batch
reg = 1e-5 # Weight decay regularizer
epoch = 50 # Number of epochs
tstEpoch = 1 # Number of epochs to test while training
gnn_layer = 1 # Number of GNN layers
use_lr_scheduler = true